language: php
php:
  - '7.3'

services:
  - docker

before_install:
  - docker build -t neelsrv30/dozetask001 .

script:
  - docker login -u="neelsrv30" -p="qwerty1234";
  - docker push neelsrv30/dozetask001;
