language: php
php:
  - '7.3'

services:
  - docker

before_install:
  - docker build -t dozetask001 .

script:
  - docker login -e="neel.97k@gmail.com" -u="neelsrv30" -p="qwerty1234";
  - docker push dozetask001;
