version: 0.2


phases:
  install:
    runtime-versions:
      php: 7.3
    commands:
      - echo Executing Install Phase
    finally:
      - echo Executing Install Finally
  pre_build:
    commands:
      - echo Executing Pre Build Phase
    finally:
      - echo Executing Pre Build Finally
  build:
    commands:
      - php --version
    commands:
      - echo Executing Build Phase
    finally:
      - echo Executing Install Finally
  post_build:
    commands:
      - echo Executing Post Build Phase
    finally:
      - echo Executing Post Build Finally
artifacts:
  files:
      - '**/*'
